Email_notification/Email_notification/Email_notification/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('mysite/', include('mysite.urls')),
    path('admin/', admin.site.urls),
]

Email_notification/Email_notification/mysite/urls.py
from . import views
from django.urls import path


app_name = 'mysite'
urlpatterns = [
    path('login/', views.loginpage, name='login'),
    path('register/', views.registerpage, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('admin/', views.admin, name='admin'),
    path('send_email/', views.send_email, name="send_email"),
    path('home/', views.home, name='home'),
    path('forms/', views.forms, name='forms'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('add_application_form_submission/', views.add_application_form_submission,
         name='add_application_form_submission'),

    ]

Email_notification/Email_notification/mysite/models.py
from django.db import models


class Application(models.Model):
    first_name = models.CharField(max_length=40)
    second_name = models.CharField(max_length=40)
    email = models.CharField(max_length=60)
    phone_no = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    interest = models.CharField(max_length=20)
    age_group = models.CharField(max_length=5)

Email_notification/Email_notification/mysite/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Email_notification/Email_notification/mysite/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib.auth import authenticate, logout, login
from django.contrib import messages
from .models import Application
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail


# registration things


def loginpage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if user.is_superuser or user.is_staff:
                return redirect('mysite:admin')
            else:
                return redirect('mysite:home')
        else:
            messages.info(request, '  Username OR password is incorrect. Try again')

    context = {}
    return render(request, 'registration/login.html', context)


def registerpage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mysite:login')

    context = {'form': form}
    return render(request, 'registration/register.html', context)


def logoutUser(request):
    logout(request)
    return redirect('mysite:login')


# notifier things


@login_required(login_url='mysite:login')
def admin(request):
    return render(request, 'mysite/admin.html')


@login_required(login_url='mysite:login')
def send_email(request):

    city = request.POST["inputCity"]
    interest = request.POST["inputInterest"]
    age_group = request.POST["inputAgegroup"]
    message = request.POST["message"]

    all_applications = Application.objects.all()

    # sending email

    for application in all_applications:
        if application.city == city or city == 'All':
            if application.interest == interest or interest == 'All':
                if application.age_group == age_group or age_group == 'All':
                    send_mail(
                        'Notifier: notification, Mr/Mrs ' + application.first_name,
                        message,
                        application.email,
                        ['emailnotifierwebclub@gmail.com', application.email],
                    )

    return render(request, 'mysite/admin.html', {'city': city, 'interest': interest, 'age_group': age_group})


@login_required(login_url='mysite:login')
def home(request):
    return render(request, 'mysite/home.html')


@login_required(login_url='mysite:login')
def forms(request):
    return render(request, 'mysite/Forms.html')


@login_required(login_url='mysite:login')
def aboutus(request):
    return render(request, 'mysite/aboutus.html')


@login_required(login_url='mysite:login')
def add_application_form_submission(request):

    first_name = request.POST["inputFirstname"]
    second_name = request.POST["inputSecondname"]
    email = request.POST["inputEmail4"]
    phone_no = request.POST["inputPhoneno"]
    address = request.POST["inputAddress"]
    city = request.POST["inputCity"]
    interest = request.POST["inputType"]
    age_group = request.POST["inputexperience"]
    message = 'Thank you for registering and using  Notifier'

    # adding application to database
    application = Application(first_name=first_name, second_name=second_name, email=email, phone_no=phone_no,
                              address=address, city=city, interest=interest, age_group=age_group)
    application.save()

    # sending email

    send_mail(
        'Notifier: Your first notification, Mr/Mrs ' + first_name,
        message,
        email,
        ['emailnotifierwebclub@gmail.com', email],
    )

    return render(request, 'mysite/Forms.html', {'first_name': first_name, 'second_name': second_name})

Email_notification/Email_notification/mysite/templates/mysite/Forms.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>Forms</title>
</head>
<style>
     .navbar-dark {
       background-color: #1a0033 !important;
      }
      .bg-primary {
        background-color: #1a0033 !important;
      }
</style>
<body>

    <!-- navbar -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'mysite:home' %}" style="padding-left:250px;"><img src="{% static 'images/logo4.png' %}" height="50px" width="100px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" >
                    <a class="nav-link active" href="{% url 'mysite:home' %}" style="padding-left:100px;">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link active" href="{% url 'mysite:aboutus' %}" style="padding-left:50px;">About us</a>
                </li>
                <li class="nav-item active " >
                    <a class="nav-link " href="{% url 'mysite:forms' %}" style="padding-left:50px;">Forms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#" style="padding-left:50px;">User: {{request.user}}<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link active" href="{% url 'mysite:logout' %}" style="padding-left:50px;">Logout<span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <span class="navbar-text">
            </span>
        </div>
    </nav>
    <br><br>


    {% if first_name %}

    <!-- conformation message  -->

    <center><br><br>
        <h2>Thank you {{first_name}} {{second_name}} !!</h2>
        <p>We have received your application and will respond shortly via email.</p>
    </center><br><br>
    <center>
        <a href="{% url 'mysite:forms' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Go back</a>
    </center>

    {% else %}

    <!-- form content -->

    <div class="container">
        <center><h1 style="padding-bottom:50px;"><b>Form instructions</b></h1></center>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-12 col-sm-6 ml-5">
                <p>Notifier sends emails based on information that you provide us in-order to reduce unwanted
                    notifications and spamming. So please select options that are relevant to you and the options that
                    interests you. </p>
                <ul>
                    <li>Email: the email which receives the notifications.</li>
                    <li>Options: Notifications will be related to these topics.</li>
                    <li>Checkbox: Please tick the check before submission.</li>
                </ul>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm">
                <img class="ml-3" src="{% static 'images/email.png' %}" height="170px" width="170px">
            </div>
        </div>
    </div>

    <center>
    <div style="width:800px;padding-top:80px;">
    <div class="card bg-dark text-white">
            <div class="container" style="background-color: #1f004d;"><br><br>
                <h2 style="text-shadow: 2px 2px #000;font-weight: 700; color: ;text-align:center;">EMAIL FORM</h2><br>
                <div class="container">
                    <form method="POST" action="{% url 'mysite:add_application_form_submission' %}">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputFirstname">First name</label>
                                <input type="text" class="form-control" id="inputFirstname" placeholder="First name" name="inputFirstname" required>
                             </div>
                            <div class="form-group col-md-6">
                                <label for="inputSecondname">Second name</label>
                                <input type="text" class="form-control" id="inputSecondname" placeholder="Second name" name="inputSecondname" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Email</label>
                                <input type="email" class="form-control" id="inputEmail4" placeholder="abc@mail.com" name="inputEmail4" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPhoneno">Phone no</label>
                                <input type="text" class="form-control" id="inputPhoneno" placeholder="Phone no" name="inputPhoneno" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputAddress">Address</label>
                            <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St ..." name="inputAddress" required>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="inputCity">City</label>
                                <select class="form-control" id="inputCity" name="inputCity" required>
                                    <option selected>Choose...</option>
                                    <option>Bangalore</option>
                                    <option>Chennai</option>
                                    <option>Mumbai</option>
                                    <option>Delhi</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputType">Interest</label>
                                <select id="inputType" class="form-control" name="inputType" required>
                                    <option selected>Choose...</option>
                                    <option>Sports</option>
                                    <option>Food</option>
                                    <option>Music/Dance</option>
                                    <option>Science</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputexperience">Age group</label>
                                <select id="inputexperience" class="form-control" name="inputexperience" required>
                                    <option selected>Choose...</option>
                                    <option>0-15</option>
                                    <option>15-25</option>
                                    <option>25-40</option>
                                    <option>40+</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="gridCheck" name="gridCheck" required>
                                    <label class="form-check-label" for="gridCheck">
                                        I assure that the given information is true.
                                    </label>
                                </div>
                             </div>
                        </div>
                        <center><button type="submit" class="btn btn-primary">Submit</button></center>
                    </form>
                </div><br><br>
            </div>
    </div>
    </div>
    </center>
    <br><br>

    {% endif %}

</body>
</html>

Email_notification/Email_notification/mysite/templates/mysite/aboutus.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>About Us</title>
</head>

<style>
.navbar-dark {
       background-color: #1a0033 !important;
      }
.bg-primary {
        background-color: #1a0033 !important;
      }
</style>

<body>

    <!-- navbar -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'mysite:home' %}" style="padding-left:250px;"><img src="{% static 'images/logo4.png' %}" height="50px" width="100px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" >
                    <a class="nav-link active" href="{% url 'mysite:home' %}" style="padding-left:100px;">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link active" href="{% url 'mysite:aboutus' %}" style="padding-left:50px;">About us</a>
                </li>
                <li class="nav-item " >
                    <a class="nav-link active" href="{% url 'mysite:forms' %}" style="padding-left:50px;">Forms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#" style="padding-left:50px;">User: {{request.user}}<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link active" href="{% url 'mysite:logout' %}" style="padding-left:50px;">Logout<span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <span class="navbar-text">
            </span>
        </div>
    </nav>
    <br><br><br><br><br><br>

    <!-- page content-->

    <div class="container">
        <center><h1 style="padding-bottom:20px;"><b>About Us </b></h1></center>
        <div class="row">
            <div class="col-12 col-sm-3">
                    <img  src="{% static 'images/history2.jpg' %}" height="170px" width="200px">
            </div>
            <div class="col-sm">
                <p style="padding-top:20px;">Started in 2020, Notifier quickly established itself as a notification icon par excellence in India.
                    With its unique feature emailing according to the interests of the users we are able to reduce spamming
                    to a great extent and increasing user satisfaction . Therefore Notifier enjoys patronage
                    from the A-list clientele in India .
                </p>
                <p>Notifier traces its humble beginnings to <em>The notifications </em>, a successful website started by
                    our CEO, Mr. Kausthub TM, that featured for the first time the world's best website.
                </p>
            </div>
        </div>
    </div>

    <!-- card content-->

    <div class="container" style="padding-top:100px;padding-bottom:150px;">
        <div class="row row-content">
            <div class="col-12 col-sm-3" style="padding-top:70px;"></div>
            <div class="col-sm-6">
                <div class="card">
                    <h3 class="card-header bg-primary text-white">Facts At a Glance</h3>
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-6">Started</dt>
                            <dd class="col-6">6 Oct. 2020</dd>
                            <dt class="col-6">Major Stake Holder</dt>
                            <dd class="col-6">HK Fine Foods Inc.</dd>
                            <dt class="col-6">No of users</dt>
                            <dd class="col-6">1,250,375</dd>
                            <dt class="col-6">Employees</dt>
                            <dd class="col-6">40</dd>
                        </dl>
                    </div>
                </div>
            </div><
            <div class="col-12" style="padding-top:40px;">
                <div class="card card-body bg-light">
                    <blockquote class="blockquote">
                        <p class="mb-0">Awareness is the first step to action. They have to know something is going on to know to do something about it.</p>
                        <footer class="blockquote-footer">Derick Virgil</footer>
                    </blockquote>
                </div>
            </div>
        </div>
    </div> <br><br><br>




</body>
</html>

Email_notification/Email_notification/mysite/templates/mysite/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>Home</title>
</head>

<style>
.navbar-dark {
       background-color: #1a0033 !important;
      }
.bg-primary {
        background-color: #1a0033 !important;
      }
.btn-primary {
       background-color: #5200cc !important;
       }
</style>

<body>

    <!-- navbar -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'mysite:home' %}" style="padding-left:250px;"><img src="{% static 'images/logo4.png' %}" height="50px" width="100px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" >
                    <a class="nav-link active" href="{% url 'mysite:home' %}" style="padding-left:100px;">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link active" href="{% url 'mysite:aboutus' %}" style="padding-left:50px;">About us</a>
                </li>
                <li class="nav-item " >
                    <a class="nav-link active" href="{% url 'mysite:forms' %}" style="padding-left:50px;">Forms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#" style="padding-left:50px;">User: {{request.user}}<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link active" href="{% url 'mysite:logout' %}" style="padding-left:50px;">Logout<span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <span class="navbar-text">
            </span>
        </div>
    </nav>
    <br><br><br><br><br><br>


    <!-- page content-->

    <div class="container" style="padding-bottom:150px;">
        <center><img src="{% static 'images/logo4.png' %}" height="200px" width="400px"></center>
        <p class="lead">
          <h5 style="text-align:center;">MOTTO: " Awareness - the key in life "</h5>
          <h5 style="text-align:center;">VISION: " To provide necessary and relevant info to people how seek it. "</h5>
        <hr class="my-4">
        <div class="row" style="padding-top:120px;">
            <div class="col-12 col-sm-8 ml-5">
                <p><b>Notifier</b> keeps you informed and up to date by providing you with all the necessary and relevant
                  information. The Notifier notifies you with events, and stuff happening around you according to your
                  interests. The notifications will be sent via emails and these notifications will be related to
                  information you provide when u fill the form. We promise you that there will be no spamming and we try to
                  make notifications as relevant as possible.
                </p>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm">
                <img class="ml-3" src="{% static 'images/who.jpg' %}" height="170px" width="170px">
            </div>
        </div>
    </div>



    <div class="container" style="border: 2px solid black;border-radius: 5px;background-color:#1a0033 ;color:white;">
        <br>
        <center><p><b>Please fill the form so we can understand u better and so u can receive more relevant notifications !! </b></p></center>
        <div class="d-flex justify-content-center">
            <a href="{% url 'mysite:forms' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Fill form !!</a>
         </div>
        <br>
    </div>
    <br><br><br>

</body>
</html>